<a href="https://colab.research.google.com/github/GitBerg/Machine_Learning_Study/blob/master/Aprendizagem%20bayesiana/Machine_Learning_Aprendizagem_bayesiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install plotly --upgrade


     |████████████████████████████████| 13.2MB 285kB/s 
  Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Naïve bayes

In [14]:
from sklearn.naive_bayes import GaussianNB

**Base risco de crédito**

In [4]:
base_risc_credit = pd.read_csv("/content/risco_credito.csv")

In [5]:
base_risc_credit

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [6]:
X_risc_credit = base_risc_credit.iloc[:, 0:4].values

In [7]:
X_risc_credit

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [8]:
y_risc_credit = base_risc_credit.iloc[:, 4].values
y_risc_credit

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantias = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [11]:
X_risc_credit[:,0] = label_encoder_historia.fit_transform(X_risc_credit[:,0])
X_risc_credit[:,1] = label_encoder_divida.fit_transform(X_risc_credit[:,1])
X_risc_credit[:,2] = label_encoder_garantias.fit_transform(X_risc_credit[:,2])
X_risc_credit[:,3] = label_encoder_renda.fit_transform(X_risc_credit[:,3])

In [12]:
X_risc_credit

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [13]:
import pickle
with open('risc_credit.pkl', 'wb') as f:
  pickle.dump([X_risc_credit, y_risc_credit], f)

In [15]:
naive_risc_credit = GaussianNB()
naive_risc_credit.fit(X_risc_credit, y_risc_credit)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
#Boa(0), dívidaAlta(0), nenhuma(1), renda > 35(2)
#ruim(2), dívidaAlta(0), adequada(0), renda < 15(0)
previsao = naive_risc_credit.predict([[0,0,1,2], [2,0,0,0]])

In [17]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [18]:
naive_risc_credit.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [19]:
naive_risc_credit.class_count_

array([6., 5., 3.])

In [20]:
naive_risc_credit.class_prior_

array([0.42857143, 0.35714286, 0.21428571])