<a href="https://colab.research.google.com/github/GitBerg/Machine_Learning_Study/blob/master/04-Aprendizagem%20por%20regras/Machine_Learning_Aprendizagem_Por_Regras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Aprendizagem por regras**

In [1]:
!pip install plotly --upgrade

     |████████████████████████████████| 13.2MB 5.1MB/s 
  Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
!pip install Orange3

In [4]:
import Orange

#**Base Risco De Crédito**

In [7]:
base_risc_credit = Orange.data.Table('risco_credito_regras.csv')

In [8]:
base_risc_credit

[[ruim, alta, nenhuma, 0_15 | alto],
 [desconhecida, alta, nenhuma, 15_35 | alto],
 [desconhecida, baixa, nenhuma, 15_35 | moderado],
 [desconhecida, baixa, nenhuma, acima_35 | alto],
 [desconhecida, baixa, nenhuma, acima_35 | baixo],
 ...
]

In [9]:
base_risc_credit.domain

[historia, divida, garantias, renda | risco]

In [11]:
cn2 = Orange.classification.rules.CN2Learner()
regras_risc_credit = cn2(base_risc_credit)

In [12]:
for regras in regras_risc_credit.rule_list:
  print(regras)

IF renda==0_15 THEN risco=alto 
IF historia==boa AND divida!=alta THEN risco=baixo 
IF historia==boa AND garantias!=nenhuma THEN risco=baixo 
IF historia==boa AND renda!=15_35 THEN risco=baixo 
IF historia==boa THEN risco=moderado 
IF divida==alta THEN risco=alto 
IF historia!=desconhecida THEN risco=moderado 
IF garantias==adequada THEN risco=baixo 
IF renda==15_35 THEN risco=moderado 
IF historia==desconhecida THEN risco=alto 
IF TRUE THEN risco=alto 


In [13]:
previsoes = regras_risc_credit([['boa', 'alta', 'nenhuma', 'acima_35'],['ruim','alta', 'adequada', '0_15']])
previsoes

array([1, 0])

In [15]:
base_risc_credit.domain.class_var.values

('alto', 'baixo', 'moderado')

In [18]:
for i in previsoes:
  print(base_risc_credit.domain.class_var.values[i])

baixo
alto


#**Base Credit Data**

In [19]:
base_credit = Orange.data.Table('credit_data_regras.csv')

In [20]:
base_credit

[[66155.9, 59.017, 8106.53 | 0],
 [34415.2, 48.1172, 6564.75 | 0],
 [57317.2, 63.108, 8020.95 | 0],
 [42709.5, 45.752, 6103.64 | 0],
 [66952.7, 18.5843, 8770.1 | 1],
 ...
]

In [21]:
base_credit.domain

[income, age, loan | default]

In [23]:
base_dividida = Orange.evaluation.testing.sample(base_credit, n = 0.25)
base_dividida

([[41285.4, 22.9111, 532.1 | 0],
  [34730.2, 63.3762, 818.508 | 0],
  [36116.4, 22.5359, 1494.98 | 0],
  [49292.3, 20.6223, 967.135 | 0],
  [41174.8, 52.3394, 2888.44 | 0],
  ...
 ], [[54925.5, 40.8056, 554.488 | 0],
  [57676.7, 20.6656, 10504.7 | 1],
  [56510.8, 47.3083, 9255.44 | 0],
  [41255.9, 45.5833, 5296.91 | 0],
  [22372.5, 31.493, 1118.93 | 0],
  ...
 ])

In [24]:
base_dividida[0]

[[41285.4, 22.9111, 532.1 | 0],
 [34730.2, 63.3762, 818.508 | 0],
 [36116.4, 22.5359, 1494.98 | 0],
 [49292.3, 20.6223, 967.135 | 0],
 [41174.8, 52.3394, 2888.44 | 0],
 ...
]

In [25]:
base_dividida[1]

[[54925.5, 40.8056, 554.488 | 0],
 [57676.7, 20.6656, 10504.7 | 1],
 [56510.8, 47.3083, 9255.44 | 0],
 [41255.9, 45.5833, 5296.91 | 0],
 [22372.5, 31.493, 1118.93 | 0],
 ...
]

In [26]:
base_treinamento = base_dividida[1]
base_teste = base_dividida[0]

In [27]:
len(base_treinamento), len(base_teste)

(1500, 500)

In [28]:
cn2 = Orange.classification.rules.CN2Learner()
regras_credit = cn2(base_treinamento)

In [29]:
for regras in regras_credit.rule_list:
  print(regras)

IF age>=34.9257164876908 THEN default=0 
IF loan<=2495.13299137587 AND income>=20145.9885970689 THEN default=0 
IF loan>=7181.4785525792595 AND loan>=8034.74777409028 THEN default=1 
IF income>=58132.4712652713 THEN default=0 
IF loan>=6342.56790924236 THEN default=1 
IF income>=46801.274286117405 AND income>=50501.7266888171 THEN default=0 
IF loan>=5862.83302915672 THEN default=1 
IF income>=45971.133494749694 THEN default=0 
IF loan<=3105.4430213977303 AND income>=27407.056202646298 THEN default=0 
IF loan>=5193.83819663771 THEN default=1 
IF age>=34.7514377613552 THEN default=1 
IF age>=34.7410444347188 THEN default=0 
IF loan>=5154.909842680399 THEN default=0 
IF loan>=5061.77783089573 THEN default=1 
IF loan>=5036.25528047363 THEN default=0 
IF loan>=4849.33378471958 THEN default=1 
IF loan>=4749.06867530672 THEN default=0 
IF income<=31702.3342987522 AND loan>=3665.88089899456 THEN default=1 
IF income>=31702.3342987522 AND income>=38423.0842860416 THEN default=0 
IF income<=317

In [30]:
previsoes = Orange.evaluation.testing.TestOnTestData(base_treinamento, base_teste,[lambda testdata: regras_credit])

In [31]:
previsoes

In [32]:
Orange.evaluation.CA(previsoes)

array([0.978])

#**Classificador base -> Majority Learner**

**Base Credit Data**

In [34]:
base_credit.domain

[income, age, loan | default]

In [36]:
majority = Orange.classification.MajorityLearner()

In [37]:
previsoes = Orange.evaluation.testing.TestOnTestData(base_credit, base_credit,[majority])

In [38]:
Orange.evaluation.CA(previsoes)

array([0.8585])

In [ ]:
for registro in base_credit:
  print(registro.get_class())

In [42]:
from collections import Counter
Counter(str(registro.get_class())for registro in base_credit)

Counter({'0': 1717, '1': 283})

#**Base Census**

In [43]:
base_census = Orange.data.Table('/content/census_regras.csv')

In [44]:
base_census.domain

[age, workclass, final-weight, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loos, hour-per-week, native-country | income]

In [45]:
previsoes = Orange.evaluation.testing.TestOnTestData(base_census, base_census, [majority])

In [46]:
Orange.evaluation.CA(previsoes)

array([0.75919044])

In [47]:
Counter(str(registro.get_class()) for registro in base_census)

Counter({'<=50K': 24720, '>50K': 7841})